### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by ahmedabbas81** [pinellolab/STREAM_atac#2]
Hello,

How long does it take to finish a scATAC-seq library having around 5200 cells? 

It ran since yesterday using k-mer, k=7 and did not finish. How many CPUs should I assign to job? Should I use GPU? should I use motifs faster? And are motifs accurate enough? 

Thanks

**Comment by huidongchen** [comment]
Hi, 

You current setting looks fine to me. K-mer and motifs should give relatively similar results. In our experiments, using kmers works slightly better than using motifs.

Are you using the newest version `v0.3.5`? If not, please make sure to update it to the latest version.

The running time also depends on how many jobs you are using (Unfortunately GPU is not supported yet). If you are only using one cpu, several hours would be expected. If possible, you can try as many cores as possible. Just for your reference, ~5k 10x PBMCs cells, using 44 cores, it finished within half an hour.

**Comment by ahmedabbas81** [comment]
Thank you,

It only worked on the cluster of GPUs and finished. On the other usual cluster, it either does not finish or make out of memory error. Do you know why it works on the GPU partition if it does not support GPU?

Also, how much memory should I specify in order not to get out of memory error? And if I use a dense library (due to imputation by some method), how much approximate memory should I ask for?

And how can I obtain siscovery of transcription factors important for lineage commitment like Fig 6c? And can I obtain it with motifs option? Or I should use kmer?

Thank you

**Comment by huidongchen** [comment]
Given such information I can't say much about GPU part. But as long as it works on your cluster, I guess it is fine.

For 5k cells, ~10GB should be good.

Re fig6c, after we got marker kmers, we used Tomtom to map them to known TF motifs. For more details, please check out the section `STREAM analysis on scATAC-seq data` in our manuscript.

**Comment by huidongchen** [comment]
Since these questions are more about the practical usage of STREAM instead of software issues, I'm closing it now. But you are more than welcome to continue this thread here.

**Comment by ahmedabbas81** [comment]
How can I ask for a specific cell type to be the starting node?

And this site: http://stream.pinellolab.org/
does not upload files (Visualize section)

Thank you

**Comment by ahmedabbas81** [comment]
Hello,

I am trying to get the trajectory to the output of a recent method used for imputation of scATAC-seq data. It gave me 3 intances of NA in the zscore file. Is there a solution for this?

Thank you

**Comment by ahmedabbas81** [comment]
Hi,
I hope I get an answer for the previous questions.

I have 3 libraries with 7000 cells or more. I am giving them 48 cores and they did not finish in 16 hours. Should I just give them more hours? or they cannot finish at all?
Thanks

**Comment by huidongchen** [comment]
Addressed at https://github.com/pinellolab/STREAM_atac/issues/3
