### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by ahmedabbas81** [pinellolab/STREAM_atac#3]
1- How can I ask for a specific cell type to be the starting node?

2- And this site: http://stream.pinellolab.org/
does not upload files (Visualize section)

3- I am trying to get the trajectory to the output of a recent method used for imputation of scATAC-seq data. It gave me 3 intances of NA in the zscore file. Is there a solution for this?

4- I have 3 libraries with 7000 cells or more. I am giving them 48 cores and they did not finish in 24 hours. Should I just give them more hours? or they cannot finish at all?

Please let me know if I should send my questions by email or to another website.
Thanks

**Comment by huidongchen** [comment]
Hi , 

Re your questions, please see my answers below:

> 1- How can I ask for a specific cell type to be the starting node?

You can first check which branch your cell type of interest falls onto using `st.plot_visualization_2D()` or `st.plot_flat_tree()` . Once the branch id is determined, you can specify the corresponding node as the starting node.

> 2- And this site: http://stream.pinellolab.org/
does not upload files (Visualize section)

The website is currently depreciated. We are moving the website part to STREAM gene pattern notebook. https://notebook.genepattern.org/services/sharing/notebooks/379/preview/

> 3- I am trying to get the trajectory to the output of a recent method used for imputation of scATAC-seq data. It gave me 3 intances of NA in the zscore file. Is there a solution for this?

STREAM internally calls package `ChromVAR`. sometime chromVAR may generate NA values. You can replace `na` with `0`.

> 4- I have 3 libraries with 7000 cells or more. I am giving them 48 cores and they did not finish in 24 hours. Should I just give them more hours? or they cannot finish at all?

It should not take that long. Can you show me the log file? which step is it stuck in?

**Comment by ahmedabbas81** [comment]
Thank you,

This is a copy of log file:


```
- STREAM single cell ATAC-seq preprocessing steps -
Version 0.3.5

[1] "Using 48 cores..."
[1] "Read in regions ..."
[1] "Read in samples ..."
[1] "Read in counts ..."
[1] "Add GC bias ..."

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

[1] "Filter peaks ..."
[1] "Get background peaks ..."
[1] "motif matching..."
[1] "Computing motif deviations..."
slurmstepd: error: *** JOB 1097027 ON sumner038 CANCELLED AT 2020-03-29T18:02:26 DUE TO TIME LIMIT ***
-------------------------------------------------------------
SUMNER/WINTER EPILOGUE
-------------------------------------------------------------
Job ID: 1097027
Cluster: slurm_cluster
User/Group: root/jaxuser
State: TIMEOUT (exit code 0)
Nodes: 1
Cores per node: 48
CPU Utilized: 47-07:24:06
CPU Efficiency: 98.55% of 48-00:07:12 core-walltime
Job Wall-clock time: 1-00:00:09
Memory Utilized: 64.37 GB
Memory Efficiency: 33.53% of 192.00 GB
-------------------------------------------------------------
       JobID  User   State    CPUTime Exit     MaxRSS        NodeList  Partition                   ReqTRES              Submit               Start                 End    Elapsed 
------------ ----- ------- ---------- ---- ---------- --------------- ---------- ------------------------- ------------------- ------------------- ------------------- ---------- 
1097027      abba+ TIMEOUT 48-00:07:12  0:0                  sumner038    compute billing=48,cpu=48,mem=19+ 2020-03-28T18:02:15 2020-03-28T18:02:17 2020-03-29T18:02:26 1-00:00:09 
1097027.bat+       CANCEL+ 48-00:12:48 0:15  65918.27M       sumner038                                      2020-03-28T18:02:17 2020-03-28T18:02:17 2020-03-29T18:02:33 1-00:00:16 
1097027.ext+       COMPLE+ 48-00:07:12  0:0          0       sumner038                                      2020-03-28T18:02:17 2020-03-28T18:02:17 2020-03-29T18:02:26 1-00:00:09 
-------------------------------------------------------------
```

**Comment by huidongchen** [comment]
hmmm, the log file looks fine to me. In my experience, I tried it on ~12k cells on the machine with 1T RAM and 44 cores. it finished within two 1.2 hours. Not sure if it's the compatibility issue of python and R. 

Can you try to run this R script (https://github.com/pinellolab/STREAM_atac/blob/master/stream_atac/run_preprocess.R) directly to see if you are able to gets through the step `Computing motif deviations...`

**Comment by ahmedabbas81** [comment]
Thank you,

It gave results for other 3 libraries.

I am beginner in R. Please tell me what command to run?

Thank you

**Comment by huidongchen** [comment]
Make sure you are in the same conda env you created for STREAM analysis,

It's similar to STREAM command line. Please refer to the tutorial https://github.com/pinellolab/STREAM_atac#tutorial. You can replace `stream_atac` with `Rscript run_preprocess.R`

E.g. you can run it as `Rscript run_preprocess.R -c count_file.tsv.gz -r region_file.bed.gz -s sample_file.tsv.gz -g hg19 -f kmer -k 7 --n_jobs 3 -o stream_output`

**Comment by ahmedabbas81** [comment]
Hello,

it gave me this error:
`/cm/local/apps/slurm/var/spool/job1111669/slurm_script: line 10: ./run_preprocess.R: Permission denied`

I am sorry, I am very beginner in this.
Can you please tell me what is the problem?

Thanks

**Comment by ahmedabbas81** [comment]
Another question please, for the starting node, in the output folder, there are many folders S0, S1, S2, ...
These are all the options for starting nodes, right?
I am asking because it is not clear how to use the commands `st.plot_visualization_2D()` or `st.plot_flat_tree()` and how to specify the starting node after that.

Also, in the folders S0, S1, ..., the same cell type in different folders has different pseudotimes, is that expected and correct. I mean some cell type in a folder has pseudotime = 0 and in another folder it has pseudotime 0,016 for example.

The third question, in some folders of S0, S1, ..., The pseudotime range is from 0 - 0.032 for example and for the same library in other folders the range is from 0 - 0.04. Is that correct and expected, or I have something wrong.

Thank you

**Comment by ahmedabbas81** [comment]
One more question please. 

> Is there a way to get the pseudotimes of every cell in a text file. For example, I want to draw a boxplot for pseudotimes for the cell type LT-HSC for example. So, I am asking for pseudotimes for cells and I will get cells of each type and draw the boxplot or violin plot.

pseudotime is stored in `adata.obs`. you can save it as a text file. e.g. `adata.obs.to_csv('yourfile.txt',sep='\t')`

**Comment by ahmedabbas81** [comment]
For the R script. I just managed to run it. No need to answer its question.

Sorry for the too many questions :)

Thanks

**Comment by ahmedabbas81** [comment]
Hello,
I have one more question,

I run stream_atac using this command: 
`stream_atac -c ./filtered_peak_bc_matrix/matrix.mtx -r ./filtered_peak_bc_matrix/peaks.bed -s ./filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g hg19 -f motif --n_jobs 3 -o stream_output`

and use the output zscores in this next command:
`$ stream --atac -m zscore.tsv.gz -l cell_label.tsv.gz -c cell_label_color.tsv.gz -o out_folder`

In the zscore file, I keep only the cells that I know their labels and filter out the cells that were filtered in the QC steps in the scATAC-seq analysis. I mean that in `stream_atac` command, it takes the raw data without any filtering of any cells and returns zscores for all cells. In the zscore file, I remove the columns corresponding to about 5% of cells and then feed the new zscore file to the second step `stream` command

Is there anything wrong in what I do?
Also, These are the only two commands I need, right? 

Sorry for the many questions. Looking forward for your answers

Thank you

**Comment by huidongchen** [comment]
> Another question please, for the starting node, in the output folder, there are many folders S0, S1, S2, ...
> These are all the options for starting nodes, right?

Yes

> I am asking because it is not clear how to use the commands `st.plot_visualization_2D()` or `st.plot_flat_tree()` and how to specify the starting node after that.

Since the graph might be learnt in high-dimensional space (>3D), it will be very difficult to imagine what the graph (more specifically , tree structure) looks like. So these two functions are simply designed to visualize the cells or tree structure in 2D. Based on the prior labels or marker genes of the cells, these two 'overview' plots helps users determine the starting node.

> Also, in the folders S0, S1, ..., the same cell type in different folders has different pseudotimes, is that expected and correct. I mean some cell type in a folder has pseudotime = 0 and in another folder it has pseudotime 0,016 for example.

Yeah, this is expected. For each cell, 'pseudotime' is defined as the distance (the length of curve) from start node to the cell's position in the manifold. With different start nodes, the obtained pseudotime will change accordingly.
> 
> The third question, in some folders of S0, S1, ..., The pseudotime range is from 0 - 0.032 for example and for the same library in other folders the range is from 0 - 0.04. Is that correct and expected, or I have something wrong.

Again. 'pseudotime' is defined as the distance (the length of curve) from start node to the cell's position in the manifold so the difference in range is expected.
> 
> Thank you

**Comment by huidongchen** [comment]
> I run stream_atac using this command:
> `stream_atac -c ./filtered_peak_bc_matrix/matrix.mtx -r ./filtered_peak_bc_matrix/peaks.bed -s ./filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g hg19 -f motif --n_jobs 3 -o stream_output`
> 
> and use the output zscores in this next command:
> `$ stream --atac -m zscore.tsv.gz -l cell_label.tsv.gz -c cell_label_color.tsv.gz -o out_folder`
> 
> In the zscore file, I keep only the cells that I know their labels and filter out the cells that were filtered in the QC steps in the scATAC-seq analysis. I mean that in `stream_atac` command, it takes the raw data without any filtering of any cells and returns zscores for all cells. In the zscore file, I remove the columns corresponding to about 5% of cells and then feed the new zscore file to the second step `stream` command
> 
> Is there anything wrong in what I do?
> Also, These are the only two commands I need, right?

Your commands look fine to me. These are the two steps you need for a preliminary analysis. You might need to fine-tune your parameters based on the output figures if necessary.

**Comment by ahmedabbas81** [comment]
Thank you for your answer,

These two questions are really important for my project,

1- Is it wrong to remove columns corresponding to the cells that I do not know their types from the zscore.tsv file and use the new zscore.tsv file (after removing some columns) to visualize the trajectory of the remaining cells?

2- Is there a command to have the pseudotimes of cells in a text file relative to a specific starting node.

Thank you and very sorry for disturbance in these difficult period. Hope you are safe and healthy

**Comment by huidongchen** [comment]
> 1- Is it wrong to remove columns corresponding to the cells that I do not know their types from the zscore.tsv file and use the new zscore.tsv file (after removing some columns) to visualize the trajectory of the remaining cells?

I think you don't have to remove them. You can simply label them as 'unknown'. The trajectory analysis along with marker feature analysis might aid in defining these 'unknown' cells types.

> 2- Is there a command to have the pseudotimes of cells in a text file relative to a specific starting node.

These is no such command.  but this information can be easily pulled out from the variable `adata.obs`. The columns that have `_pseudotime` store the pseudotime you need, e.g. , `S1_pseudotime` has the pseudotimes of cells relative to the starting node `S1`. 

> Thank you and very sorry for disturbance in these difficult period. Hope you are safe and healthy

Thank you! Stay safe and well too!
