### ISSUE TITLE
How to proceed in the absence of cell_label files

### ISSUE THREAD

**Issue by sylestiel** [pinellolab/STREAM_atac#6]
Hi,

 When working with 10x Genomics single cell ATAC-seq data processed with Cell Ranger what should we put in for
st.add_cell_labels(adata,file_name='./cell_label.tsv.gz')
st.add_cell_colors(adata,file_name='./cell_label_color.tsv.gz')

If i were to skip this step it appears to be a problem in the downstream steps where a color command needs to be filled
st.plot_dimension_reduction(adata,color=['label'], show_graph=False,show_text=False,)

How can I address this issue?

Thank you!

**Comment by huidongchen** [comment]
Hi ,

As shown in our [tutorial](https://nbviewer.jupyter.org/github/pinellolab/STREAM/blob/master/tutorial/1.2.STREAM_scRNA-seq%20%28Multifurcation%29.ipynb?flush_cache=true), you can simply ignore the parameter `file_name` when either labels or label colors are not available. By default, 'unknown' will be used as cell label.

```python
st.add_cell_labels(adata)
st.add_cell_colors(adata)
```

**Comment by sylestiel** [comment]
Thank you!
